repos:
-   repo: local
    hooks:
    -   id: update-docs
        name: Generate updated docs
        entry: poetry run python dbtwiz/utils/docs.py
        language: system
        pass_filenames: false
        always_run: false
        files: '^dbtwiz/.*\.py$'
